schema_version = "1.0.0"
id = "final_topology"
name = "Final Topology - Inverse Subdivide"
version = "2.2.1"
tagline = "Professional subdivision modelling tools, simply magic"
maintainer = "Vilem Duha, BlenderKit <admin@blenderkit.com>"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/BlenderKit/final_topology"
copyright = [
    "2023 Vilem Duha",
]
